DROP TABLE IF EXISTS user_profile;
DROP TABLE IF EXISTS user_address;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS user_groups;
DROP TYPE IF EXIST address_type;
