alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

global:
  scrape_interval: 10s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/default.rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: grafana
    static_configs:
      - targets:
          - grafana:3000

  - job_name: token-svc
    static_configs:
      - targets:
          - api:4001

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: redis-exporter
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: postgres-exporter
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger:14269

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          # - https://dev.homerow.tech/api/v2/health/ping
          - http://api:4000/health/ping
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      # - source_labels: [__address__]
      #   regex: (.*)(:80)?
      #   target_label: __param_target
      # - source_labels: [__param_target]
      #   regex: (.*)
      #   target_label: instance
      #   replacement: ${1}
      # - source_labels: []
      #   regex: .*
      #   target_label: __address__
      #   replacement: blackbox-exporter:9115
