global:
  slack_api_url: "{{SLACK TOKEN HERE}}"
  resolve_timeout: 1m

route:
  receiver: "slack"
  group_by: [alertname, job]

receivers:
  - name: "slack"
    slack_configs:
      - channel: "#git-workflow"
        send_resolved: true
        title: '{{ template "slack.monzo.title" . }}'
        icon_emoji: '{{ template "slack.monzo.icon_emoji" . }}'
        color: '{{ template "slack.monzo.color" . }}'
        text: '{{ template "slack.monzo.text" . }}'
        actions:
          - type: button
            text: "Runbook :green_book:"
            url: "{{ (index .Alerts 0).Annotations.runbook_link }}"
            # url: "{{ .CommonAnnotations.runbook_link }}" Both work...
            style: primary
          - type: button
            text: "Dashboards :grafana:"
            url: "{{ (index .Alerts 0).Annotations.dashboard_link }}"
            style: secondary
          - type: button
            text: "Logs :kibana:"
            url: "{{ (index .Alerts 0).Annotations.logs_link }}"
            style: secondary
          - type: button
            text: "Tracing :jaeger:"
            url: "{{ (index .Alerts 0).Annotations.tracing_link }}"
            style: secondary

templates:
  - "/etc/alertmanager/templates/*.tmpl"
