{
 "title": "Docker Prometheus Monitoring",
 "description": "Docker Service Monitoring",
 "tags": [
  "docker",
  "node-exporter",
  "cadvisor",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,15m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Time 99th %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Request Time 95th %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "95th"
    }
   ]
  },
  {
   "title": "Request Time 90th %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "90th"
    }
   ]
  },
  {
   "title": "Request Time 50th %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Request Time Buckets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "99th Percentile By Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le,uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "95th Percentile By Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le,uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "90th Percentile By Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_histogram_ms_bucket[$interval])) by (le,uri))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Average Duration by Path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_histogram_ms_sum / http_request_duration_histogram_ms_count",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Average Duration by HTTP Method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_histogram_ms_sum / http_request_duration_histogram_ms_count) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Error/Audit Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Error %",
   "type": "graph",
   "description": "The percentage of 5xx errors (excluding /health check endpoints)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_response_total{uri!~\".*health.*\", code=~\"5..\"}[$interval])) / sum(rate(http_response_total{uri!~\".*health.*\"}[$interval]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(http_response_total{uri!~\".*health.*\", code=~\"4..\"}[$interval])) / sum(rate(http_response_total{uri!~\".*health.*\"}[$interval]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Audit Logs/sec",
   "type": "graph",
   "description": "The rate of audit log events per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(audit_total[1m])) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Request/Response Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "HTTP Request/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_total{uri!=\"\", job=~\"token-svc\"}[$interval])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Request URI/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_total{uri!=\"\"}[$interval])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Request Method/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_request_total{uri!=\"\"}[$interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Response Code/sec",
   "type": "graph",
   "description": "The breakout of HTTP response code rate (per second)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_response_total[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "graph",
   "description": "The percentage breakdown of each HTTP Response Code.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_response_total{code=~\"2..\"}[$interval])) / sum(rate(http_response_total[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(http_response_total{code=~\"3..\"}[$interval])) / sum(rate(http_response_total[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(http_response_total{uri!~\".*health.*\", code=~\"4..\"}[$interval])) / sum(rate(http_response_total{uri!~\".*health.*\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(http_response_total{uri!~\".*health.*\", code=~\"5..\"}[$interval])) / sum(rate(http_response_total{uri!~\".*health.*\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
     "targets": [
      { "expr": "ALERTS" }
     ]
    }
   ]
  },
  { "title": "Host Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Prometheus Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 60 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[1m] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total[$interval] ) )) / count(node_cpu_seconds_total{mode=\"system\"}) * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 82 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes - container_fs_usage_bytes) / sum(container_fs_limit_bytes)"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  },
  { "title": "Container Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  {
   "title": "Running Versions",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor  Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_memory_usage_bytes{image!=\"\", name!=\"\"}[$interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}